export const environment = {
    production: false,
    operadorURL: 'http://localhost:8080/operador/',
    authURL: 'http://localhost:8080/auth/',
    estatusURL: 'http://localhost:8080/estatusOperador/',
    gruaURL: 'http://localhost:8080/grua/',
    estatusGruaURL:'http://localhost:8080/grua-estatus/',
    clientTipoURL: 'http://localhost:8080/cliente-tipo/',
    clienteURL: 'http://localhost:8080/cliente/',
    vehiculoURL:'http://localhost:8080/vehiculo/',
    servicioURL: 'http://localhost:8080/servicio/',
    estatusOperador: 'http://localhost:8080/estatus-operador/',
    estatusGrua: 'http://localhost:8080/estatus-grua/',
    marcaURL: 'http://localhost:8080/marca/',
    modeloURL: 'http://localhost:8080/modelo/',
    transaccionURL: 'http://localhost:8080/transaccion-service/',
    tiposVehiculoURL: 'http://localhost:8080/tipos-vehiculo/',
    excelOpeURL:'http://localhost:8080/excel-operadores/download/excel',
    excelGruaURL: 'http://localhost:8080/excel-gruas/download/excel',
    apiUrl: 'http://localhost:8080',
    excelServicios: 'http://localhost:8080/excel-servicios/servicios',
    pdfUrl: 'http://localhost:8080/pdf-carta/generate/',
    cotizacionUrl:'http://localhost:8080/cotizaciones/'

  };